Dev/info command
ascmitc/mhl pull request #39
Opened 2020-11-05 17:03 UTC by ptrpfn

Added the single-file variant of the info command, updated README for usage. Also moved the tool name and version to __version__.py

2020-11-13 11:03 UTC, asmpfn requested changes
There are some general requirements I would like to ask for to add with a new command that are not included yet:

* A test case that covers the new command and contains the simple case as well as one more complex case e.g. with multiple histories
  * see the other test cases for create and record as example
  * you can use the simple_mhl_history and nested_mhl_histories fixtures so you don't need to build an existing history yourself
* The command help should describe shortly what the command does, currently it just says `Info`

I found some issues during testing that should probably be addressed:
* For the `-sf` option I can not pass a relative string, only an absolute string seems to work, but for the `-rp` option a relative path seems to work
* If the file for the `-sf` option is a relative path that exists no error is shown, only `None:`
* If not specifying a root path the most top level mhl history is used instead of the one nearest to the file given
  * e.g. try to get the info for the following file in the scenario 5 output folder: `examples/scenarios/Output/scenario_05/file_server/Reels/A003R2EC/Clips/A003C012_141024_R2EC.mov`
  * it will use the top level history found in `Reels`
* The command syntax does not exactly work as described in the readme, `-sf` requires that a path is given like `-rp`.
  * So I can't use it like `./ascmhl.py info -sf -rp /root/path /path/to/file` but have to use e.g. `./ascmhl.py info -rp /root/path -sf /path/to/file`.
  * Can we change it so that the path is an argument instead and the `sf` option is just a flag like `-v`?

2020-11-19 10:56 UTC, ptr-rennstoff commented
fixed all problems, corrected readme and help output, created tests

2020-11-19 10:57 UTC, ptr-rennstoff commented
also added a --version option

2020-11-19 11:29 UTC, asmpfn approved these changes

2020-11-19 11:29 UTC, merged